// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsDGv8oYY0TAncNzGFe7orsbjcsigE77U',
    appId: '1:292137139277:web:39c8cab9136825f01e3004',
    messagingSenderId: '292137139277',
    projectId: 'yeogiyo-59f27',
    authDomain: 'yeogiyo-59f27.firebaseapp.com',
    storageBucket: 'yeogiyo-59f27.firebasestorage.app',
    measurementId: 'G-P6ECEH17XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7BrDTQQp1YWpmhVvedXCSKQsOHnhw0YA',
    appId: '1:292137139277:android:15b4a3b34b8533341e3004',
    messagingSenderId: '292137139277',
    projectId: 'yeogiyo-59f27',
    storageBucket: 'yeogiyo-59f27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-FlbxPW3iZuFS2ChFv6joQAxSaHydOcw',
    appId: '1:292137139277:ios:b8f7a87590989f081e3004',
    messagingSenderId: '292137139277',
    projectId: 'yeogiyo-59f27',
    storageBucket: 'yeogiyo-59f27.firebasestorage.app',
    iosClientId: '292137139277-ur49lcl9vp5dos6mhktcj79oo00n0in8.apps.googleusercontent.com',
    iosBundleId: 'com.example.yeogiyo',
  );
}
